Two minor fixes (#251)
* Fix link error in BitStreamParser.cpp

g++ -I"../../../.." -D"_UNICODE" -D"UNICODE" -D"DEBUG" -D"_DEBUG" -MMD -MQ ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParser.o -MP -MF ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParser.o.d -Wno-error=attributes -Wno-error=write-strings -pthread -Werror -std=c++11 -fno-exceptions -fno-rtti -fvisibility=hidden -fPIC -Wno-unused-result -O0 -ggdb -m64 -c ../../../../public/samples/CPPSamples/common/BitStreamParser.cpp -o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParser.o
g++ -I"../../../.." -D"_UNICODE" -D"UNICODE" -D"DEBUG" -D"_DEBUG" -MMD -MQ ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH264.o -MP -MF ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH264.o.d -Wno-error=attributes -Wno-error=write-strings -pthread -Werror -std=c++11 -fno-exceptions -fno-rtti -fvisibility=hidden -fPIC -Wno-unused-result -O0 -ggdb -m64 -c ../../../../public/samples/CPPSamples/common/BitStreamParserH264.cpp -o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH264.o
g++ -I"../../../.." -D"_UNICODE" -D"UNICODE" -D"DEBUG" -D"_DEBUG" -MMD -MQ ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH265.o -MP -MF ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH265.o.d -Wno-error=attributes -Wno-error=write-strings -pthread -Werror -std=c++11 -fno-exceptions -fno-rtti -fvisibility=hidden -fPIC -Wno-unused-result -O0 -ggdb -m64 -c ../../../../public/samples/CPPSamples/common/BitStreamParserH265.cpp -o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH265.o
g++  -Wl,--no-undefined -Wl,-rpath='$ORIGIN' -Wno-error=attributes -Wno-error=write-strings -pthread -Werror -std=c++11 -fno-exceptions -fno-rtti -fvisibility=hidden -fPIC -Wno-unused-result -O0 -ggdb -m64 -o ../../../../bin/dbg_64/SimpleROI ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/SimpleROI/SimpleROI.o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParser.o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH264.o ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParserH265.o ../../../../bin/dbg_64/build/SimpleROI/public/common/AMFFactory.o ../../../../bin/dbg_64/build/SimpleROI/public/common/AMFSTL.o ../../../../bin/dbg_64/build/SimpleROI/public/common/DataStreamFactory.o ../../../../bin/dbg_64/build/SimpleROI/public/common/DataStreamFile.o ../../../../bin/dbg_64/build/SimpleROI/public/common/DataStreamMemory.o ../../../../bin/dbg_64/build/SimpleROI/public/common/Thread.o ../../../../bin/dbg_64/build/SimpleROI/public/common/TraceAdapter.o ../../../../bin/dbg_64/build/SimpleROI/public/common/Linux/ThreadLinux.o -ldl -lm -lX11 -lGL
/usr/bin/ld: ../../../../bin/dbg_64/build/SimpleROI/public/samples/CPPSamples/common/BitStreamParser.o: in function `BitStreamParser::Create(amf::AMFDataStream*, BitStreamType, amf::AMFContext*)':
/home/rgonzalez/src/github.com/GPUOpen-LibrariesAndSDKs/AMF/amf/public/samples/CPPSamples/SimpleROI/../../../../public/samples/CPPSamples/common/BitStreamParser.cpp:111: undefined reference to `CreateIVFParser(amf::AMFDataStream*, amf::AMFContext*)'
collect2: error: ld returned 1 exit status
make[1]: *** [../../../../public/make/common_rules.mak:84: ../../../../bin/dbg_64/SimpleROI] Error 1
make[1]: Leaving directory '/home/rgonzalez/src/github.com/GPUOpen-LibrariesAndSDKs/AMF/amf/public/samples/CPPSamples/SimpleROI'
make: *** [Makefile:51: ../../public/samples/CPPSamples/SimpleROI] Error 2

* Fix expression result unused

```
../../../../public/src/components/ComponentsFFMPEG/UtilsFFMPEG.cpp:450:41: error: expression result unused [-Werror,-Wunused-value]
    case AMF_STREAM_CODEC_ID_VP9_10BIT: (AVCodecID)AMF_CODEC_VP9_10BIT;
                                        ^          ~~~~~~~~~~~~~~~~~~~
```