Fix expression result unused
```
../../../../public/src/components/ComponentsFFMPEG/UtilsFFMPEG.cpp:450:41: error: expression result unused [-Werror,-Wunused-value]
    case AMF_STREAM_CODEC_ID_VP9_10BIT: (AVCodecID)AMF_CODEC_VP9_10BIT;
                                        ^          ~~~~~~~~~~~~~~~~~~~
```